### ISSUE TITLE
multiSMC functions not ok 

### ISSUE THREAD

**Issue by oneway3124** [nchopin/particles#27] opened 2021-03-24 12:36 UTC
results = particles.multiSMC(fk=fk_model, N=100, nruns=30, qmc={'SMC':False, 'SQMC':True})

C:\ProgramData\Anaconda3\envs\particles\lib\multiprocessing\popen_spawn_win32.py in init(self, process_obj)
91 try:
92 reduction.dump(prep_data, to_child)
---> 93 reduction.dump(process_obj, to_child)
94 finally:
95 set_spawning_popen(None)

C:\ProgramData\Anaconda3\envs\particles\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
58 def dump(obj, file, protocol=None):
59 '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60 ForkingPickler(file, protocol).dump(obj)
61
62 #

PicklingError: Can't pickle <function _identity at 0x000002D7B4A67A60>: it's not the same object as particles.core._identity

**Comment by nchopin** [comment] 2021-03-24 12:43
Hi, 
please provide more detail:

* give a minimal, reproducible example, see here: 
 https://stackoverflow.com/help/minimal-reproducible-example
 i.e a self-contained piece of code that generates this error. 

* give your configuration. From the above, I can imagine you are using Anaconda on Windows? 

Thx

**Comment by oneway3124** [comment] 2021-03-24 12:53
Yes, I am using the anaconda on windows.

The reproducible example as follows

![image](https://user-images.githubusercontent.com/3787176/112313481-da6ce800-8ce2-11eb-848c-42bf6c5a1275.png)


Please copy test.ipynb file into the particle folder.
[test.zip](https://github.com/nchopin/particles/files/6197309/test.zip)


Thx

**Comment by nchopin** [comment] 2021-03-24 13:08
works fine on my computer. Which version of Python are using?

**Comment by oneway3124** [comment] 2021-03-24 15:05
python version: 3.9.2
![QQ图片20210324230346](https://user-images.githubusercontent.com/3787176/112333227-5e2fd000-8cf5-11eb-9cd3-f0ecde6f18ad.png)

**Comment by AdrienCorenflos** [comment] 2021-03-25 17:30
Long story short, this is a problem due to the combination of Windows and of Jupyter. I will look into making these compatible (it will probably require changing the parallelisation backend and therefore will take some time).

**In the meantime**, I can suggest the three following different solutions:
1. Use Linux instead of Windows on your machine (or similarly, use a virtual machine under Windows that would be running say Ubuntu, see for instance https://windowsreport.com/virtual-machine-software/)
2. Run you code in a python script instead of a notebook, BUT make sure to guard the code using a if __name__ == "__main__", similarly as [here](https://github.com/nchopin/particles/blob/master/book/smoothing/offline_smoothing.py)
3. Run your code in a webhosted environment. For example [here](https://colab.research.google.com/drive/19pDJw8e5Za_GcbeB4QR9L0qM6mQcJOln?usp=sharing) is your code running on Google Colab (I only had to install particles first, see the first line)

Adrien

**Comment by oneway3124** [comment] 2021-03-26 02:53
![微信截图_20210326105133](https://user-images.githubusercontent.com/3787176/112570579-3fc6f300-8e21-11eb-945d-7d5b2c085557.png)

Right now, I test your  "test.ipynb" on Google Colab. I found that your python version is 3.7.10.

So I downgrade my python version to this version.  The result is not ok for me.
So I will try your other solution some minutes later.

**Comment by AdrienCorenflos** [comment] 2021-03-26 07:46
This is not a problem with Python versions, but with the fact you are using Windows.

**Comment by nchopin** [comment] 2021-03-26 08:50
Hi, 
You can also fix the problem by adding option nprocs=1; that is, change this line 

> results = particles.multiSMC(fk=fk_model, N=100, nruns=30, qmc={'SMC':False, 'SQMC':True})

as follows: 

> results = particles.multiSMC(fk=fk_model, N=100, nprocs=1, nruns=30, qmc={'SMC':False, 'SQMC':True})

This means: use only one CPU; effectively this disables multiprocessing. 

As Adrien explained, multiprocessing does not work on jupyter on Windows. And multiSMC uses multiprocessing by default. Maybe I should change this, and make nprocs=1 the default.

**Comment by oneway3124** [comment] 2021-03-26 08:54
Thanks for your instant response!!

# results = particles.multiSMC(fk=fk_model, N=100, nruns=30, qmc={'SMC':False, 'SQMC':True})
results = particles.multiSMC(fk=fk_model, N=100, nprocs=1, nruns=30, qmc={'SMC':False, 'SQMC':True})
plt.figure()

The result is as follows,
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-84d754e90332> in <module>
      1 # results = particles.multiSMC(fk=fk_model, N=100, nruns=30, qmc={'SMC':False, 'SQMC':True})
----> 2 results = particles.multiSMC(fk=fk_model, N=100, nprocs=1, nruns=30, qmc={'SMC':False, 'SQMC':True})
      3 plt.figure()

~\Desktop\particles\particles\core.py in multiSMC(nruns, nprocs, out_func, collect, **args)
    522     return utils.multiplexer(f=f, nruns=nruns, nprocs=nprocs, seeding=True,
    523                              protected_args={'collect': collect},
--> 524                              **args)

~\Desktop\particles\particles\utils.py in multiplexer(f, nruns, nprocs, seeding, protected_args, **args)
    269             op['seed'] = seed
    270     # the actual work happens here
--> 271     return distribute_work(f, inputs, outputs, nprocs=nprocs)
    272 

~\Desktop\particles\particles\utils.py in distribute_work(f, inputs, outputs, nprocs, out_key)
    169     if nprocs <= 1:
    170         return [add_to_dict(op, f(**ip), key=out_key)
--> 171                 for ip, op in zip(inputs, outputs)]
    172 
    173     # multiprocessing

~\Desktop\particles\particles\utils.py in <listcomp>(.0)
    169     if nprocs <= 1:
    170         return [add_to_dict(op, f(**ip), key=out_key)
--> 171                 for ip, op in zip(inputs, outputs)]
    172 
    173     # multiprocessing

~\Desktop\particles\particles\utils.py in __call__(self, **kwargs)
    212         if seed:
    213             random.seed(seed)
--> 214         return self.func(**kwargs)
    215 
    216 

~\Desktop\particles\particles\core.py in __call__(self, **kwargs)
    432     def __call__(self, **kwargs):
    433         pf = SMC(**kwargs)
--> 434         pf.run()
    435         return self.fun(pf)
    436 

~\Desktop\particles\particles\utils.py in timed_method(self, **kwargs)
     86     def timed_method(self, **kwargs):
     87         starting_time = time.perf_counter()
---> 88         out = method(self, **kwargs)
     89         self.cpu_time = time.perf_counter() - starting_time
     90         return out

~\Desktop\particles\particles\core.py in run(self)
    418            command only.
    419         """
--> 420         for _ in self:
    421             pass
    422 

~\Desktop\particles\particles\core.py in __next__(self)
    384             raise StopIteration
    385         if self.t == 0:
--> 386             self.generate_particles()
    387         else:
    388             self.setup_auxiliary_weights()  # APF

~\Desktop\particles\particles\core.py in generate_particles(self)
    327     def generate_particles(self):
    328         if self.qmc:
--> 329             u = qmc.sobol(self.N, self.fk.du).squeeze()
    330             # squeeze: must be (N,) if du=1
    331             self.X = self.fk.Gamma0(u)

~\Desktop\particles\particles\qmc.py in sobol(N, dim, scrambled)
     67     while True:
     68         seed = np.random.randint(max_int_32)
---> 69         out = lowdiscrepancy.sobol(N, dim, scrambled, seed, 1, 0)
     70         if np.all(out < 1.) and np.all(out > 0.):
     71             return out

NameError: name 'lowdiscrepancy' is not defined

**Comment by oneway3124** [comment] 2021-03-26 08:55
This result is run in the jupyter on ubuntu systems!

**Comment by oneway3124** [comment] 2021-03-26 09:00
![Uploading 微信截图_20210326170021.png…]()

**Comment by nchopin** [comment] 2021-03-26 09:02
Your new error message is because you are trying to run the QMC (quasi-Monte Carlo) variant of SMC, but the qmc module was not properly installed on your system (i.e. the fotran program lowdiscrepancy was not compiled). If you don't care about QMC, just do this: 

> results = particles.multiSMC(fk=fk_model, N=100, nruns=30, qmc=False)

But of course the plots below will not work. If you do want to run QMC, please read carefully the installation instructions, and check you have a fortran compiler on your system.

**Comment by oneway3124** [comment] 2021-03-26 09:13
OK, thank you very much! Thank you for your patient guidance!

**Comment by AdrienCorenflos** [comment] 2021-03-26 12:00
Note that there is a Fortran compiler on Colab, so you could simply port your experiments there.

**Comment by oneway3124** [comment] 2021-03-26 12:08
@AdrienCorenflos @nchopin
Thanks for your kindly and instant help.
I have fixed this problem quickly. At the same time,  I have run the code in Anaconda on Windows successfully.
![12](https://user-images.githubusercontent.com/3787176/112628879-7d05a200-8e6e-11eb-978f-1ffc6e678fb3.png)
The requirements of my conda on windows.
[particles_requirements_window_conda.txt](https://github.com/nchopin/particles/files/6211659/particles_requirements_window_conda.txt)

**Comment by nchopin** [comment] 2021-03-30 15:02
PR #28 should fix the issue permanently, so I'm closing this thread, but feel free to open a new one if needed.

**Closed by nchopin** 2021-03-30 15:02 UTC
